create table department (id bigint generated by default as identity, department_name varchar(255), description varchar(255), primary key (id))
create table employee (id bigint generated by default as identity, email_id varchar(255), first_name varchar(255), last_name varchar(255), dept_id bigint, primary key (id))


